### ISSUE TITLE
KafkaSource is overriding my original kafka message cloud event type

### ISSUE THREAD

**Issue by xqianwang** [knative-sandbox/eventing-kafka#1285] opened 2023-01-20 01:31 UTC
**Describe the bug**

I have messages in kafka following cloud event spec. Following is the original header values in topic:

`ce_datacontenttype: application/json, ce_entityType: TENANT_ENTITY, ce_group: d008cc77-c3b0-4a94-8e6e-b5649ca7e8d7, ce_id: 98a9f24e-d36b-449f-96a8-6ab675e613b4, ce_source: mdm-instance-payload-out, ce_specversion: 1.0, ce_subject: instance-payload-message, ce_tenant: d008cc77-c3b0-4a94-8e6e-b5649ca7e8d7, ce_time: 2023-01-19T22:30:24.860213GMT, ce_type: Credentialing.WorkFlow.CREATE, content-type: application/json`

 But when I got message in my function, it throws error like below:

`2023-01-20 00:34:07,645 ERROR [io.qua.funqy] (executor-thread-0) Couldn't map CloudEvent type: 'dev.knative.kafka.event' to a function.`

Looks like kafka source is overriding my original ce-type to be dev.knative.kafka.event.  This behaviour also cause my broker and trigger filtering function not working. 

 **Expected behavior**
The original cloud event attributes should be used for calling function. 
 **To Reproduce**
Steps to reproduce the behavior.

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by pierDipi** [comment] 2023-01-20 09:27
Thanks for reporting @xqianwang, would you mind sharing how did you install KafkaSource? there are multiple implementations of the KafkaSource API, so knowing which one you're using might help identifying the problem

**Comment by xqianwang** [comment] 2023-01-20 22:19
Hi @pierDipi ,  thank you for replying me.
`apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
 name: instance-payload-source
spec:
  consumerGroup: event-processor-group
  bootstrapServers:
  - xx-public.xxxxx.xxxxxx.xxx.kafka.us-east-1.amazonaws.com:9196
  - xx-public.xxxxx.xxxxxx.xxx.kafka.us-east-1.amazonaws.com:9196
  - xx-public.xxxxx.xxxxxx.xxx.kafka.us-east-1.amazonaws.com:9196
  topics:
  - demo
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: kafka-broker
  net:
    sasl:
      enable: true
      user:
        secretKeyRef:
          name: secret
          key: user
      password:
        secretKeyRef:
          name: secret
          key: password
      type:
        secretKeyRef:
          name: secret
          key: sasl.mechanism
    tls:
      enable: true
`
This is how I created it.

**Comment by pierDipi** [comment] 2023-01-23 08:47
Would you mind sharing how did you send records to Kafka and how it looks like?

**Comment by xqianwang** [comment] 2023-01-24 04:20
Please check the attached pic for kafka record. 
![image](https://user-images.githubusercontent.com/29929974/214211456-6024a377-e2be-4933-bd80-5385ccca522b.png)

**Comment by xqianwang** [comment] 2023-01-24 04:21
And I send Kafka message using Quarkus smallrye kafka cloudevent extention https://quarkus.io/blog/kafka-cloud-events/

**Comment by pierDipi** [comment] 2023-01-24 08:44
@xqianwang, I think the problem is that the record is not a properly formatted CloudEvent, because, for example, the 2 time value: `2023-01-19T22:30:24.860213GMT` or `2023-01-23T12:23:11.65224America/Toronto` are not following https://www.rfc-editor.org/rfc/rfc3339 since the spec requires that RFC (https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md#type-system) for timestamps

**Comment by pierDipi** [comment] 2023-01-24 08:48
would mind sharing Quarkus code you used to create the CloudEvent, in particular, the time part?

**Comment by pierDipi** [comment] 2023-01-24 08:51
FYI @cescoffier

**Comment by cescoffier** [comment] 2023-01-24 09:06
I would be surprised that the connector does not do the right thing for dates. If that's the case, please open an issue on Smallrye reactive messaging.

**Comment by xqianwang** [comment] 2023-01-24 14:23
Actually it's my code that generate the date which is not following the proper format. I will change the code and see if it will fix the issue that I saw. Thank you!

**Comment by xqianwang** [comment] 2023-01-24 21:08
@cescoffier  Actually I think the connector does not do right thing for ZonedDateTime
This is how I generate kafka message:
```
OutgoingCloudEventMetadataBuilder builder = OutgoingCloudEventMetadata.builder()
                .withId(id)
                .withType(type)
                .withSource(URI.create(DEFAULT_PAYLOAD_SOURCE))
                .withSubject(DEFAULT_PAYLOAD_SUBJECT)
                .withTimestamp(ZonedDateTime.now())
                .withDataContentType(MediaType.APPLICATION_JSON);
        if (instance.getGroupId() != null) {
            builder.withExtension(GROUP_ATTRIBUTE, instance.getGroupId().toString());
        }
        if (instance.getTenantId() != null) {
            builder.withExtension(TENANT_ATTRIBUTE, instance.getTenantId().toString());
        }
        if (context != null && !Strings.isNullOrEmpty(context.get(ENTITY_TYPE_ATTRIBUTE))) {
            builder.withExtension(ENTITY_TYPE_ATTRIBUTE, context.get(ENTITY_TYPE_ATTRIBUTE));
        }
        return Message.of(payload).addMetadata(builder.build());
```

**Comment by cescoffier** [comment] 2023-01-25 06:31
Please open an issue on Smallrye reactive messaging with a reproducer. We
will have a look.

**Comment by pierDipi** [comment] 2023-04-12 09:35
@xqianwang I'm closing this issue, it'd be great if you can provide a link to the Smallrye issue for other users running in the same issue

**Closed by pierDipi** 2023-04-12 09:35 UTC
Labels: kind/bug
