### ISSUE TITLE
[source] Missing event because of missing retry

### ISSUE THREAD

**Issue by steven0711dong** [knative-sandbox/eventing-kafka#664] opened 2021-05-27 19:35 UTC
**Describe the bug**
Missing events because retry is missing 

 **Expected behavior**
We expect when a sink post fails, we should retry so we don't have missing events 

 **To Reproduce**
Produce half million messages to a topic of more than 100 partitions and have all messages forwarded to a sink with no delay. 

 **Knative release version**

 **Additional context**
Add any other context about the problem here such as proposed priority

**Comment by lionelvillard** [comment] 2021-05-28 13:02
Duplicate of https://github.com/knative-sandbox/eventing-kafka/issues/639

**Comment by steven0711dong** [comment] 2021-05-28 15:22
@lionelvillard Like @slinkydeveloper said, I think supporting delivery spec could be a good option. What do you think?

**Comment by steven0711dong** [comment] 2021-05-28 15:23
Do not close on this issue yet. Whether the missing events due to retry works or not depends on our tests results. We need multiple tests to confirm whether the fix works or not.

**Closed** 2021-06-08 14:15 UTC
Labels: kind/bug
